### ISSUE TITLE
UUID 보내면 동아리장인지 아닌지 확인하는 서비스 생성

### ISSUE THREAD

**Issue by mkthefreeman** [DMS-SMS/v1-service-club#42]
UUID를 보내면 동아리장이라면 해당 동아리에 대한 정보 그런거 보내주면 좋을거 같아용. 만약 동아리장이 아니라면 404 이런거 보내는식으로

**Comment by parkjinhong03** [comment]
@mallycrip 요청하신 서비스에 대한 서비스 이름 및 기능 설명입니다.

- 학생용 서비스인 **GetClubUUIDWithLeaderUUID**가 그 기능을 합니다.
- 전달한 학생 UUID가 Leader인 동아리가 존재할 경우, **그 동아리의 UUID**를 반환합니다.
- 반대로 존재하지 않을 경우엔, **404 NOT FOUND**를 반환합니다.
